M48
; DRILL file {KiCad 9.0.6} date 2026-04-30T20:31:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-30T20:31:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X160.112Y-83.078
X175.0Y-81.25
X176.828Y-96.138
T2
X140.25Y-102.75
X149.75Y-82.75
X171.83Y-105.2
M30
